remove all reviews associated with a product when product is deleted
khareemah/e-commerce-API pull request #17
Opened 2023-05-16 16:25 UTC by khareemah

Please review

2023-05-21 11:40 UTC, fisayo-dmg requested changes

2023-05-21 11:40 UTC, fisayo-dmg commented on controllers/reviewController.js
>  const getSingleProductReviews = async (req, res) => {
what happens when the product id does not exist?

2023-05-21 13:00 UTC, khareemah commented on controllers/reviewController.js
>  const getSingleProductReviews = async (req, res) => {
An empty array would be returned

2023-05-21 14:36 UTC, fisayo-dmg commented on controllers/reviewController.js
>  const getSingleProductReviews = async (req, res) => {
but in many other parts of the code you have returned an error with a message that the product doesn't exist, any reason why you are not keeping it consistent with that?

2023-05-21 15:50 UTC, khareemah commented on controllers/reviewController.js
>  const getSingleProductReviews = async (req, res) => {
That's true, I'll uncomment the if statement

2023-05-24 20:20 UTC, fisayo-dmg approved these changes

2023-05-24 20:21 UTC, merged