create review
khareemah/e-commerce-API pull request #5
Opened 2023-05-09 08:03 UTC by khareemah

Please review create review controller

2023-05-10 10:37 UTC, fisayo-dmg requested changes
did this code run properly?

2023-05-10 10:37 UTC, fisayo-dmg commented on app.js
> +const reviewRouter = require('./route/reviewRoute');
I think you have a wrong path here, shouldn't it be `'./routes/reviewRoute'`. check the other comment.

2023-05-10 10:37 UTC, fisayo-dmg commented on routes/reviewController.js
I think you meant to name this file `reviewRoute.js`

2023-05-10 13:03 UTC, khareemah commented on routes/reviewController.js
I have tested the route, its working properly now

2023-05-10 13:05 UTC, khareemah commented
i have effected the changes

2023-05-10 13:28 UTC, fisayo-dmg approved these changes
nice.

2023-05-10 13:55 UTC, fisayo-dmg approved these changes

2023-05-10 14:01 UTC, fisayo-dmg approved these changes

2023-05-10 14:01 UTC, fisayo-dmg approved these changes

2023-05-10 14:02 UTC, fisayo-dmg approved these changes

2023-05-10 14:03 UTC, fisayo-dmg approved these changes

2023-05-10 14:11 UTC, fisayo-dmg approved these changes

2023-05-10 14:15 UTC, fisayo-dmg approved these changes

2023-05-12 14:29 UTC, fisayo-dmg requested changes
test

2023-05-12 14:31 UTC, closed without merging