get all reviews and single review
khareemah/e-commerce-API pull request #8
Opened 2023-05-13 03:16 UTC by khareemah

Please review and merge changes

2023-05-13 16:32 UTC, fisayo-dmg requested changes

2023-05-13 16:32 UTC, fisayo-dmg commented on controllers/reviewController.js
> +    throw new CustomError.NotFoundError(`No review with if ${reviewId}`);
small typo here, I think you meant 'id' not 'if'.

2023-05-14 08:29 UTC, khareemah commented on controllers/reviewController.js
> +    throw new CustomError.NotFoundError(`No review with if ${reviewId}`);
fixed...

2023-05-15 06:22 UTC, fisayo-dmg approved these changes
nice.

2023-05-15 06:23 UTC, merged